### ISSUE TITLE
Add UI Version Number to Footer

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/dms-ui#109]
Minor useful enhancement - Add UI version # to footer.

Argo example:

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/961e4e6b-1436-4b64-bf29-4c3f82b90cf8)

**Comment by ciaranschutte** [comment]
![1.png](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/3b20d184-282c-42ab-b937-66b8fa71bfff)
![2.png](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/6e0cac36-f6d0-42d5-b37b-028bbd437224)

I like just the version number, not making the footer too busy. If you'd like any text like the Argo example please let know @b-f-chan

**Comment by b-f-chan** [comment]
Thanks @ciaranschutte, I agree with @kcullion suggestions, let's do the following:

- Let's move the version number to the right-hand side of the footer so all the info is in one place
- Can place the text per the following screenshot:

![image](https://user-images.githubusercontent.com/40768946/153081626-f3aee70a-69c8-4d54-9066-eb4ed2cbbf93.png)

For example, `Help | DMS UI v1.3 powered by` [Overture Logo]

**Comment by b-f-chan** [comment]
Note, the `UI v.13 powered by` text should not be hyperlinked

Only `DMS` should be linked to the DMS installation docs (this link is already there, just saying please don't link the new text being added :) ) - Thanks!

**Comment by ciaranschutte** [comment]
PR for QA: https://github.com/overture-stack/dms-ui/pull/133

**Comment by b-f-chan** [comment]
Tested successfully in QA:

- Version number appears in right hand footer in correct position
- Existing external links work as expected

Ready to move to staging
