### ISSUE TITLE
DMS UI Security Alerts

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/dms-ui#127]
![image.png](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/1205955d-b390-4806-b8b4-7d66b719576b)

**Comment by ciaranschutte** [comment]
@anncatton @akachru-github do I need specific permissions to see dependabot alerts? I don't have that option in the menu for dms-ui

**Comment by akachru-github** [comment]
added you @ciaranschutte , try once more?

**Comment by ciaranschutte** [comment]
PR for QA: https://github.com/overture-stack/dms-ui/pull/133

**Comment by b-f-chan** [comment]
Tested successfully staging.  Following basic smoke tests were done successfully:

- Login via Google, GitHub, LinkedIn, ORCiD
- Logout
- View user profile
- Generate, copy, revoke token
- Filtering with facet panel in file explorer
- Change view in results table (paging, show/hide columns, sorting)
- Download results table TSV and manifest
- Click external links in various areas of portal

Ready to move to release
