### ISSUE TITLE
Jbrowse feedback: Selection logic & errors

### ISSUE THREAD

**Issue by samrichca** [overture-stack/dms-ui#171]
- Make errors more explicit. (See number 7 & 8) https://github.com/overture-stack/dms-jbrowse-components/issues/18#issuecomment-1611950245
- Improve selection logic. If the user selects more than X files, regardless of compatibility, block Jbrowse. Update tooltip wording to reflect this.
- Make sure Jbrowse compatibility state is accurate (see Patrick's bug about selecting/unselecting controlled/open access files).

---

- Disable Jbrowse button & show tooltip (& error message in the Jbrowse tab, if it was previously opened):
    - If user selects >5 files: "Too many files have been selected. A maximum of 5 files may be selected at once."
    - If user selects 0 files: "0 files have been selected. Please select 1-5 files to launch JBrowse."
    - If the user selects 1-5 files and none are compatible: use current wording.
- If the user selects 1-5 files and some aren't compatible, on the Jbrowse tab, show the visualization & selected files table, and show the yellow warning message with a list of incompatible filenames.

**Comment by b-f-chan** [comment]
All errors tested successfully on QA, closing
