### ISSUE TITLE
Feedback for DMS-UI Layout & Styling

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/dms-ui#32]
Single ticket to fix any feedback from these DMS-UI tickets: #2, #3, #5, #6, #8, #41

As discussed with @anncatton, the issues are minor enough we can group in 1 ticket.  Can break out later if any task gets too large.

**Feedback:**

- [x] Add hover state for login buttons - Change dark blue background & border around icon to #4F85AE
- [x] Style the menu items default state - right now it's just showing active state for data explorer (default state is shown for the data explorer on: https://zpl.io/VkjvJy8)
- [x] Overture logo in footer should link to overture.bio and open in a new window
- [x]  Login instructions should not be bold
- [x] Workers/equipment image should be placed to the left of the green background more, and responsive as mentioned earlier; suggestion from @kcullion is once layout starts to break, hide the image and teal-green band
- [x] FIx minimum height on the side bar: 
 ![image](https://user-images.githubusercontent.com/15824252/98135710-26330800-1e8e-11eb-847f-88d1fd2f6696.png)
- [x]  Browser tab missing fav icon, use same as overture.bio
- [x] Browser tab missing page title, suggest following: "Overture DMS - Login", "Overture DMS - Data Explorer", "Overture DMS - User Profile & Token"
- [x] URL to the data explorer should end in "/explorer", not "/repository" 
- [ ] Hide ID provider buttons based on presence of URL in config from Installer input (will be done as separate enhancement in dms-ui#82)
- [x] On Profile Page, the 2nd bullet point text is wrapping but should be on single line - Fix the width setting

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/c4ee6122-a32d-42dc-bebb-2a1c509b29d8)

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/940de376-f0b8-4980-aa4a-3d580ea8b4c8)

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/918a50cd-e53c-4b91-b4e8-d2c695b594aa)

**Comment by anncatton** [comment]
@b-f-chan just saw the note about hiding providers based on dms configuration, agree this should be done in a separate ticket

**Comment by b-f-chan** [comment]
Tested on staging:

- Login buttons now have correct hover state
- Data Explorer button now has correct default state (if not active, e.g. if you are on Login page instead)
- Logo in footer correctly links to overture.bio and opens in separate tab
- Login instructions no longer bold
- Workers/equipment image now responsive, as layout starts to break, image is hidden
- Minimum height on Data Explorer sidebar fixed, correctly spans entire window height now
- Browser tab now displays correct overture.bio fav icon
- Browser tabs now have correct page title depending on the page
- Data Explorer URL now correctly ends in "/explorer"
- 2nd bullet on profile page no longer wraps
