### ISSUE TITLE
overture / dms-ui: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/dms-ui#34]
Migrate docker image from dockerhub to ghcr registry.
App repo:
https://github.com/overture-stack/dms-ui

Update application pipeline to push newly built docker images to ghcr registry. This change must be merged into develop and master branch.
(If applicable) Update helm chart to use image from ghcr by default.
(If applicable) Redeploy all helm releases that consume this docker image

**Comment by headsoup** [comment]
Confirmed pending...

**Comment by yalturmes** [comment]
Pipeline updated to push images to dockerhub and ghcr registry. Closing ticket.
