### ISSUE TITLE
Manually Provision Default Metadata to Arranger

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/dms-ui#4]
Manually provision default metadata to Arranger to unblock deployment and testing of DMS Portal on Dev & QA (stating) environments.

This includes all the config data an Arranger Admin would typically need to setup, including but not limited, for example:

-Field mapping config
-Facet aggregation config
-Field column state config
-Etc.

Search config not included as that does not work currently in Arranger.

**NOTE:** Consensus at Sept 17, 2020 planning was to do this manual task to unblock current testing, while a longer-term solution is discussed and decided offline on how to modify Arranger to either (1) deploy as a service with sensible default config + metadata already provided, OR (2) as a "library" with a custom API service like ARGO Gateway that can handle data provisioning via an API

**Comment by b-f-chan** [comment]
Discussion with @anncatton, due to some missing services & configs on both Dev and Staging, we cannot publish SONG analyses and hence get test data indexed.

**The outstanding tasks required:**

**Dev**

- Faulty SONG config needs to be fixed to enable publishing

**Staging**

- Deploy Kafka
- Deploy Maestro
- Deploy ElasticSearch
- Configure SONG
- Other services may also require configuration

**Comment by rtisma** [comment]
@b-f-chan Deployment of arranger is blocked by https://github.com/overture-stack/arranger/issues/618. Once that ticket is fixed, arranger-server can be deployed in overture-qa and overture-staging

**Comment by b-f-chan** [comment]
Unblocked, arranger#618 is complete, Arranger has been deployed to QA and Staging.  Any issues with those deployment configs can be handled in separate tickets.

**Comment by rtisma** [comment]
@b-f-chan @akachru-github arranger has been released and deployed to both the QA and STAGING environments. I believe inorder to close this ticket, arranger.staging needs to be configured. Not sure who is supposed to do this.

**Comment by akachru-github** [comment]
@rtisma by this you mean someone goes into the Arranger UI and configures it for staging?

**Comment by rtisma** [comment]
@akachru-github correct. Im not sure what the preference is. I do have ones that i though were sensible

https://github.com/overture-stack/genomic-data-playground/tree/master/arranger-data/project/file_centric

however I think @b-f-chan needs to make that call when he is back.

**Comment by akachru-github** [comment]
Next steps: 
- Configure arranger in Staging for our "sensible defaults".
- Save these defaults to docker as the base configuration to support the DMS

**Comment by b-f-chan** [comment]
New defaults configured to reduce size of facets and table width.  Closing.
