### ISSUE TITLE
Implement User Profile Page

### ISSUE THREAD

**Issue by gokul472** [overture-stack/dms-ui#40]
Implement the user profile page per the mockups provided below

NOTE: This ticket will not include actual API integration for the generate & revoke token actions, those will be in separate ticket

Mockups & screenshots:

![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/6c6f527d-019b-42fc-bd67-88584ddbb552)

## Design link - ZEPLIN
1. Identity provider icons can be found on the login page. So this "authenticated with" section should be dynamic for any of the identity providers: https://zpl.io/2GZdPRj
2. No token: https://zpl.io/VkjvJy8
3. Generated token: https://zpl.io/VqoeRA5
4. Copied token: https://zpl.io/awKejAn
5. Expired/revoked token: https://zpl.io/VxPe5g3

## Wiki link
https://wiki.oicr.on.ca/display/OV/UI+Specs+for+DMS+Portal

**Comment by anncatton** [comment]
this page will be found under path `/user`

**Comment by anncatton** [comment]
@b-f-chan All the styles for different states (empty token, valid token, revoked) are in the code but i didn't add any functionality to the buttons so the state in overture-staging is with a token valid until `2021-02-14T15:58:37.151+0000`. Other styles can be verified once #41 is implemented!

**Comment by b-f-chan** [comment]
Thanks @anncatton - Will defer testing button states and the state of the text box until #41 is done.

In that case, the layout looks good, only one minor quibble - The second bullet is wrapping instead of showing as a single line, any particular reason for this, or just a miss?

**Comment by b-f-chan** [comment]
The wrapping issue is width setting we need to change, we will address this along with minor styling feedback in #32.  Scope of this ticket can be considered done.

**Comment by b-f-chan** [comment]
Closing as done
