### ISSUE TITLE
Upgrade Nextjs to 10.x

### ISSUE THREAD

**Issue by anncatton** [overture-stack/dms-ui#45]
Upgrade to address dependency vulnerability.

Notes
- Webpack dependencies will need to be updated

**Comment by anncatton** [comment]
This needs to be upgraded to `>=11.1.3`  as of Dec.16, 2021

**Comment by ciaranschutte** [comment]
v12 out now
- 9 => 10 no breaking changes
- 10 => 11 working, upgrade react to 17
- 11 => 12 css broken due to @zeit/css being deprecated

**Comment by ciaranschutte** [comment]
PR for QA: https://github.com/overture-stack/dms-ui/pull/133

**Comment by b-f-chan** [comment]
Tested successfully staging.  Following basic smoke tests were done successfully:

- Login via Google, GitHub, LinkedIn, ORCiD
- Logout
- View user profile
- Generate, copy, revoke token
- Filtering with facet panel in file explorer
- Change view in results table (paging, show/hide columns, sorting)
- Download results table TSV and manifest
- Click external links in various areas of portal

Ready to move to release
