### ISSUE TITLE
Portal: Do not include actions column in table

### ISSUE THREAD

**Issue by kcullion** [overture-stack/dms-ui#5]
As discussed in sprint planning, please hide/do not include the actions column that allows the user to individually download files
![image](https://user-images.githubusercontent.com/18424138/92161857-3895b480-edff-11ea-871e-edd742719cf4.png)

@gokul472 I will leave in mocks for now, as it's easier just to ask Ann not to include :)

**Comment by b-f-chan** [comment]
Testing blocked waiting on #4 to get default metadata into Arranger, will carryover to Sprint 7

**Comment by b-f-chan** [comment]
Arranger setup complete, testing on QA unblocked. Staging still missing Arranger project, I will try and set that up myself today. But will do initial test on QA as well. Unblocking issue.

**Comment by b-f-chan** [comment]
Verified column removed in QA

**Comment by rosibaj** [comment]
confirmed in staging - no action column is visible.
