### ISSUE TITLE
Pass Correct URL to Table Component for TSV Download

### ISSUE THREAD

**Issue by gokul472** [overture-stack/dms-ui#55]
The TSV download for the explorer table currently isn't working, it is trying to access the localhost instead of the server URL specified in the Arranger API's configuration

Currently, clicking the button does nothing - Once the URL is corrected, the file should download

**Comment by b-f-chan** [comment]
Blocked by arranger#644

**Comment by b-f-chan** [comment]
Actual download behaviour can't be tested until arranger#644 fixed

Scope to test for this ticket is that the download URL is no longer localhost

Tested on staging, in browser console, request is correctly going to the actual download endpoint:

- https://arranger.staging.overture.bio/dev2/download
