### ISSUE TITLE
Update Demo Portal Header & Footer

### ISSUE THREAD

**Issue by gokul472** [overture-stack/dms-ui#6]
## Objective
The objective of the ticket is to ensure to incorporate the header and footer to the demo portal.
Ensure we have the Real estate for the lab image and the lab name
Once the user is logged in: The Login button will change to the "Hello, <User name>" as shown in the design.

## Acceptance Criteria

- [x] The logo will link to the data explorer (data portal) page.
- [x] The footer will be added. It will have the 2 links. HELP and the DMS.

1) The DMS link will re-direct to the Doc Site -  **Example (These URL's are just shown as example and may change in future)**
DMS link for the DMS portal Admins: overture.bio/Documentation/DMS/For-admins/howtoinstalldms
2) The Help will re-direct the user to the doc site:
Help link for the DMS portal users: overture.bio/Documentation/DMS/For-users/DataExplorer

## Screenshot for Design
![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/c5e83fde-8a32-46ab-a1ed-64fe794eb040)

![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/d2400a8e-b80d-4665-a930-b2e8d34ab370)

## Zeplin Links
1. Default logo (and footer): https://zpl.io/2jGGXBr
2. If DMS admin chooses to put their own logo in, it replaces both the overture logo and the "Data Management System" text (should have a max-height so it fits in the header bar): eg. https://zpl.io/2ZWWv9d
3. If the DMS admin just chooses to include their lab/instutution name - that text replaces "Data Management System" text and the overture logo remains. Eg. https://zpl.io/adOOEWE
4. logged in user dropdown: https://zpl.io/VDyyMll

## Wiki link:
https://wiki.oicr.on.ca/display/OV/UI+Specs+for+DMS+Portal
pls refer to section 4 -> for changes to lab and logo name

**Comment by b-f-chan** [comment]
Testing blocked waiting on #4 to get default metadata into Arranger, will carryover to Sprint 7

**Comment by b-f-chan** [comment]
Arranger setup complete, testing on QA unblocked.  Staging still missing Arranger project, I will try and set that up myself today.  Unblocking issue.

**Comment by b-f-chan** [comment]
Feedback on footer from @kcullion - Overture logo in footer should link to overture.bio

Will address in single consolidated feedback ticket for all these screens

Will smoke test in staging once release tag deployed

**Comment by rosibaj** [comment]
tested in staging - lgtm.
