### ISSUE TITLE
Connect Login Button to EGO Auth Endpoint

### ISSUE THREAD

**Issue by gokul472** [overture-stack/dms-ui#9]
Connect the login button to the EGO auth endpoint

Start with Google as the first implementation to get one login flow working before attempting the other providers.

**NOTE:** This is NOT implementing the actual OAUTH mechanism, that is already in EGO, this is essentially hooking up the page to EGO itself

**Comment by b-f-chan** [comment]
Avoid using JWT in cookie due to security risks

**Comment by b-f-chan** [comment]
Tested in staging with the providers that are currently configured (Google, GITHUB, ORCID):

- If logging in as new user:
    - User successfully created in Ego with correct name & e-mail
    - Correct user name is displayed in header & profile page, taken from providerToken
    - Correct e-mail is displayed in profile page
    - User correctly redirected to Data Explorer after login
- If logging in as existing user:
    - Correct user name is displayed in header & profile as taken from Ego itself
    - Correct e-mail is displayed in profile page
    - User correctly redirected to Data Explorer after login
